# Generated by Django 5.2.6 on 2025-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='civility',
            field=models.CharField(default='M', max_length=100),
            preserve_default=False,
        ),
    ]
